name: test_hmm
channels:
- conda-forge
- edeno
- defaults
dependencies:
- "python>=3.8"
- hmmlearn
- numpy
- scipy
- scikit-learn
- matplotlib
- xarray
- jax
- pandas
- replay_trajectory_classification
- tensorflow
- tensorflow-probability
- patsy
- seaborn
- tqdm
- jupyter
- jupyterlab
- nb_conda
- setuptools
- flake8
- pytest
- pytest-cov
- coveralls
- black