name: test_hmm
channels:
- conda-forge
- defaults
dependencies:
- "python>=3.8"
- hmmlearn
- numpy
- scipy
- scikit-learn
- matplotlib
- xarray
- jax
- pandas
- seaborn
- tqdm
- jupyter
- jupyterlab
- nb_conda
- setuptools
- flake8
- pytest
- pytest-cov
- coveralls
- black